spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/fileupload?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  servlet:
      multipart:
        enabled: false
logging:
  level:
    com.myself.sbdiancan.dataobject.mapper: trace